In [1]:
import numpy as np

# Introduction

In [3]:
np.__version__

'1.21.5'

# Creating arrays

In [4]:
# array from a list
arr1 = np.array([10,21,32,43,54,65,76,87,98])

In [7]:
print(arr1)

[10 21 32 43 54 65 76 87 98]


In [9]:
# type of the object is ndarray and means a ndimensional same type array
type(arr1)

numpy.ndarray

In [14]:
# verificando o formato do array
arr1.shape

(9,)

# Arrays index in numpy

In [16]:
print(arr1)

[10 21 32 43 54 65 76 87 98]


In [18]:
# index 4
arr1[4]

54

In [20]:
# slicing
arr1[1:4] #last one excluded

array([21, 32, 43])

In [23]:
# list of index
indices = [1,2,5,6]
arr1[indices]

array([21, 32, 65, 76])

In [26]:
# boolean mask, or a filter!!!
mask = (arr1%2 == 0)
mask

array([ True, False,  True, False,  True, False,  True, False,  True])

In [30]:
arr1[mask] #thats important for a R user!!!!!!!!!!!!!!!!!!!!!!!!!

array([10, 32, 54, 76, 98])

In [32]:
arr1[0] = 100
arr1

array([100,  21,  32,  43,  54,  65,  76,  87,  98])

In [34]:
try:
    arr1[0] = "Novo elemento"
except:
    print("Operação não permitida")

Operação não permitida


# Funções, Métodos e atributos da array

In [36]:
arr2 = np.array([1,2,3,4,5])

print(arr2)

[1 2 3 4 5]


In [37]:
type(arr2)

numpy.ndarray

In [39]:
# cumulative sum
arr2.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)

In [40]:
# cumulative product
arr2.cumprod()

array([  1,   2,   6,  24, 120], dtype=int32)

In [41]:
# arange function creates a array conntaining a sequence between an interval
arr3 = np.arange(0,50,5)

print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [42]:
type(arr3)

numpy.ndarray

In [44]:
# shape function
np.shape(arr3)

(10,)

In [48]:
# values types
print(arr3.dtype)

int32


In [51]:
# creating an 0 array
arr4 = np.zeros(10)

print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [55]:
# creating the identity matrix
arr5 = np.eye(3)

print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
# creating a DIAGONAL matrix
arr6 = np.diag(np.array([1,2,3,4,5,6]))

print(arr6)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [179]:
arr6 = np.diag([1,2,3,4,5])

print(arr6)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [70]:
# boolean array
arr7 = np.array([False, True, True, False, True])
print(arr7)

[False  True  True False  True]


In [73]:
arr2[arr7]

array([2, 3, 5])

In [190]:
arr6[arr7,0:3]

array([[0, 2, 0],
       [0, 0, 3],
       [0, 0, 0]])

In [75]:
# String array
arr8 = np.array(["R","Python","Julia"])

Some useful Numpy functions:

In [82]:
np.linspace(0,10) #does not look stochastic, grid linear funnction prob

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [84]:
np.logspace(0,5,10)# grid log function probably

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])

# Matrix manipulation

In [93]:
# creating matrix
arr9 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [91]:
type(arr9) #continue to be an ndarray

numpy.ndarray

In [94]:
print(arr9.shape)

(3, 3)


In [169]:
# Criando uma matriz 2x3 apenas com números "1"
arr10 = np.ones(shape = (2,3))
print(arr10)


[[1. 1. 1.]
 [1. 1. 1.]]


numpy.ndarray

In [99]:
# list of list
lista = [[1,0,0],[0,1,0],[0,0,1]]

In [146]:
arr11 = np.matrix(lista)
arr11

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [147]:
type(arr11)

numpy.matrix

In [148]:
arr11.size

9

In [149]:
print(arr11.dtype)

int32


In [150]:
# matrix index
arr11[2,2]

1

In [200]:
arr11[1,]

matrix([[0, 1, 0]])

In [201]:
x = np.array([1,2]) #Numpy decide o tipo de dado
y = np.array([1.0,2.0]) #Numpy decides data type
z = np.array([1,2], dtype = np.float64) #Defining the type

In [203]:
print(x.dtype,y.dtype,z.dtype)

int32 float64 float64


In [207]:
arr12 = np.array([[12,35,10],[10,24,35]], dtype = float)
print(arr12)

[[12. 35. 10.]
 [10. 24. 35.]]


In [209]:
arr12.itemsize

8

In [210]:
arr12.nbytes

48

In [211]:
arr12.ndim

2

# Tensors and greater dimensions arrays

In [214]:
arr_3d = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])
arr_3d.shape

(2, 3, 3)

In [215]:
print(arr_3d) #tensor paralelepipedo

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


# Dealing with files in numpy

In [216]:
import os
filename = os.path.join("dataset.csv")

In [222]:
!more dataset.csv

sepal_length,sepal_width,petal_length,petal_width,species
5.1,3.5,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa
4.7,3.2,1.3,0.2,setosa
4.6,3.1,1.5,0.2,setosa
5,3.6,1.4,0.2,setosa
5.4,3.9,1.7,0.4,setosa
4.6,3.4,1.4,0.3,setosa
5,3.4,1.5,0.2,setosa
4.4,2.9,1.4,0.2,setosa
4.9,3.1,1.5,0.1,setosa
5.4,3.7,1.5,0.2,setosa
4.8,3.4,1.6,0.2,setosa
4.8,3,1.4,0.1,setosa
4.3,3,1.1,0.1,setosa
5.8,4,1.2,0.2,setosa
5.7,4.4,1.5,0.4,setosa
5.4,3.9,1.3,0.4,setosa
5.1,3.5,1.4,0.3,setosa
5.7,3.8,1.7,0.3,setosa
5.1,3.8,1.5,0.3,setosa
5.4,3.4,1.7,0.2,setosa
5.1,3.7,1.5,0.4,setosa
4.6,3.6,1,0.2,setosa
5.1,3.3,1.7,0.5,setosa
4.8,3.4,1.9,0.2,setosa
5,3,1.6,0.2,setosa
5,3.4,1.6,0.4,setosa
5.2,3.5,1.5,0.2,setosa
5.2,3.4,1.4,0.2,setosa
4.7,3.2,1.6,0.2,setosa
4.8,3.1,1.6,0.2,setosa
5.4,3.4,1.5,0.4,setosa
5.2,4.1,1.5,0.1,setosa
5.5,4.2,1.4,0.2,setosa
4.9,3.1,1.5,0.1,setosa
5,3.2,1.2,0.2,setosa
5.5,3.5,1.3,0.2,setosa
4.9,3.1,1.5,0.1,setosa
4.4,3,1.3,0.2,setosa
5.1,3.4,1.5,0.2,setosa
5,3.5,1.3,0.3,setosa
4.5,2.3,1.3,0.3,setosa
4.

In [218]:
# Carregando um dataset para dentro de um array
arr13 = np.loadtxt(filename, delimiter= ",", usecols= (0,1,2,3,), skiprows=1)

In [223]:
print(arr13)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

# Stat basics

In [225]:
arr14 = np.array([15,23,63,94,75])

In [227]:
# array mean
np.mean(arr14)

54.0

In [228]:
# array standard deviation
np.std(arr14)

30.34468652004828

In [230]:
# array variance
np.var(arr14)

920.8

In [231]:
arr14.var()

920.8

# Some math with Numpy

In [233]:
np.linalg.cholesky

<function numpy.linalg.cholesky(a)>

In [235]:
arr15 = np.arange(1,10)
print(arr15)

[1 2 3 4 5 6 7 8 9]


In [236]:
np.sum(arr15)

45

In [282]:
# row or col sum with axis parameter
arr9.sum(axis = 0)

array([12, 15, 18])

In [237]:
np.prod(arr15)

362880

In [238]:
np.cumsum(arr15)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [239]:
arr16 = np.array([3,2,1])
arr17 = np.array([1,2,3])

In [240]:
# sum of array (usual sum of vectors and matrices)
np.add(arr16, arr17)

array([4, 4, 4])

para multiplcar dois vetores ou matrizes temos duas opções: dot() e @

In [245]:
arr19 = np.array([[1,2],[3,4]])
arr20 = np.array([[5,6],[0,7]])

In [246]:
np.dot(arr19,arr20)

array([[ 5, 20],
       [15, 46]])

In [247]:
arr19 @ arr20

array([[ 5, 20],
       [15, 46]])

# Array slicing

In [249]:
arr22 = np.diag(np.arange(3))

In [250]:
print(arr22)

[[0 0 0]
 [0 1 0]
 [0 0 2]]


In [251]:
arr22[1,1]

1

In [252]:
arr22[1]

array([0, 1, 0])

In [253]:
arr22[:,2]

array([0, 0, 2])

In [254]:
arr23 = np.arange(10)

In [255]:
print(arr23)

[0 1 2 3 4 5 6 7 8 9]


In [256]:
arr23[2:9:3]

array([2, 5, 8])

In [257]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [258]:
a == b

array([False,  True, False,  True])

In [259]:
# global comparison 
np.array_equal(a,b)

False

In [260]:
arr23.min()

0

In [261]:
arr23.max()

9

In [262]:
# sum of scalar and array
arr23 + 4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [263]:
# round a array is possible

### O método flatten() é importante! Ele cria uma cópia unidimensional (ou achatada) de uma array multidimensional, mantendo a ordem da array original (

In [270]:
arr9.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [273]:
# repeat the array
np.repeat(arr23, 2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [274]:
np.tile(arr23,2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# é possível criar cópia, já que a atribuição direta será por ponteiro e não uma nova